export const SET_ALERT = 'SET_ALERT';
export const UNSET_ALERT = 'UNSET_ALERT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_LOGIN_SUCCESS_MODAL = 'SET_LOGIN_SUCCESS_MODAL';
export const GET_ALL_USERS_DATA = 'GET_ALL_USERS_DATA'; 
export const SET_SPECIFIC_USER_DATA = 'SET_SPECIFIC_USER_DATA';
export const UPDATE_SPECIFIC_USER_DATA = 'UPDATE_SPECIFIC_USER_DATA';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_ALL_USERS_DATA = 'UPDATE_ALL_USERS_DATA';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const NOT_RECOGNIZED = 'NOT_RECOGNIZED';

export const SET_LOADER = 'SET_LOADER';
export const UNSET_LOADER = 'UNSET_LOADER';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const POST_NOTIFICATIONS = 'POST_NOTIFICATIONS';
export const REPLACE_NOTIFICATION = 'REPLACE_NOTIFICATION';
export const FILTER_NOTIFICATIONS_BY_ID = 'FILTER_NOTIFICATIONS_BY_ID';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'

export const GET_SPECIFIC_UPLOAD = 'GET_SPECIFIC_UPLOAD';
export const GET_ALL_FILES_DATA = 'GET_ALL_FILES_DATA';
export const FILTER_ALL_FILES_DATA_BY_ID = 'FILTER_ALL_FILES_DATA_BY_ID';
export const GET_FAVOURITE_FILES = 'GET_FAVOURITE_FILES';
export const GET_LATEST_FILES = 'GET_LATEST_FILES';


export const GET_SPECIFIC_BLOG = 'GET_SPECIFIC_BLOG';
export const GET_ALL_BLOGS_DATA = 'GET_ALL_BLOGS_DATA';
export const FILTER_ALL_BLOGS_DATA_BY_ID = 'FILTER_ALL_BLOGS_DATA_BY_ID';

export const INTERNET_DISCONNECTED_ERROR = 'INTERNET_DISCONNECTED_ERROR';