export const SET_ALERT = 'SET_ALERT';
export const UNSET_ALERT = 'UNSET_ALERT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_LOGIN_SUCCESS_MODAL = 'SET_LOGIN_SUCCESS_MODAL';
export const UNSET_LOGIN_SUCCESS_MODAL = 'UNSET_LOGIN_SUCCESS_MODAL';
export const GET_ALL_USERS_DATA = 'GET_ALL_USERS_DATA'; 
export const GET_SPECIFIC_USER = 'GET_SPECIFIC_USER';
export const SET_SPECIFIC_USER_DATA = 'SET_SPECIFIC_USER_DATA';
export const UNSET_SPECIFIC_USER_DATA = 'UNSET_SPECIFIC_USER_DATA';
export const GET_USER_UPLOADS = 'GET_USER_UPLOADS';
export const FILTER_ALL_USERS_DATA_BY_ID = 'FILTER_ALL_USERS_DATA_BY_ID';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const NOT_RECOGNIZED = 'NOT_RECOGNIZED';

export const SET_LOADER = 'SET_LOADER';
export const UNSET_LOADER = 'UNSET_LOADER';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const FILTER_NOTIFICATIONS_BY_ID = 'FILTER_NOTIFICATIONS_BY_ID'

export const GET_SPECIFIC_UPLOAD = 'GET_SPECIFIC_UPLOAD';
export const GET_ALL_FILES_DATA = 'GET_ALL_FILES_DATA';
export const FILTER_ALL_FILES_DATA_BY_ID = 'FILTER_ALL_FILES_DATA_BY_ID';